import type {GameLevel, GameRound} from "../games.ts";

type Goal = [label: string, question: string | GameRound["questions"][number], evidence?: string];

function round(id: string, title: string, limit: number, brief: string, ...goals: Goal[]): GameRound {
    return {
        id, title, limit, brief, goalCount: goals.length,
        labels: goals.map(([label]) => label),
        questions: goals.map(([label, question, evidence]) => (typeof question === "string" ? {
            type: "choice",
            instruction: question,
            criteria: ["This detail is absent or contradicted.", evidence ?? label]
        } : question))
    };
}

export const lockLevels: GameLevel[] = [
    {id: 1, title: "Small messages", skill: "Give a simple message three useful jobs", estimatedDuration: "2-3 min", rounds: [
        round("1-1", "A small emergency", 120,
            "Name an animal, ask for help, and make it urgent",
            ["Name an animal", {type: "noul", instruction: "Does the text contain an actual animal name? A category label is not an animal name.", criteria: ["An animal name like cat, dog, or fox appears in the text.", "No animal name appears in the text."]}],
            ["Ask for help", {type: "noul", instruction: "Does the writer ask someone for help? Answer yes if the writer requests assistance or asks someone to help. Answer no otherwise.", criteria: ["Yes", "No"]}],
            ["Call for immediate action", {type: "noul", instruction: "Does the text explicitly call for immediate action? Answer yes if the message requests action now, immediately, or describes an emergency. Answer no otherwise.", criteria: ["Yes", "No"]}]),
        round("1-2", "Share the ride", 120,
            "Ask for a lift, say where you need to go, and offer to pay for fuel",
            ["Ask for a lift", {type: "noul", instruction: "Does the writer ask someone for a ride?", criteria: ["", ""]}],
            ["Name your destination", {type: "choice", instruction: "What does the message establish?",
                criteria: ["No destination is given; requesting a ride alone does not name one.", "The message gives somewhere to travel to, such as a station, library, home, or another destination."]}],
            ["Offer to pay for fuel", {type: "noul", instruction: "Does the writer offer to cover the fuel cost?",
                criteria: ["The writer offers to pay for fuel.", "This is not stated in the text."]}]),
        round("1-3", "One spare cookie", 120,
            "Offer a cookie, name its flavor, and say you baked it yourself",
            ["Offer a cookie", "Does the writer offer someone a cookie?",
                "The writer offers the reader a cookie."],
            ["Name its flavor", "Does the text name the flavor of a cookie?",
                "A cookie flavor is named."],
            ["Say you baked it yourself", {type: "noul", instruction: "Does the writer say they baked the cookies themselves?",
                criteria: ["", ""]}])
    ]},
    {id: 2, title: "Make it useful", skill: "Give someone enough information to act", estimatedDuration: "3-5 min", rounds: [
        round("2-1", "Parcel patrol", 140,
            "Tell a neighbor you have their parcel, where to collect it, and when",
            ["Say you have their parcel", {type: "noul", instruction: "Does the message say the writer has a delivery for the recipient?",
                criteria: ["The writer has received or is holding the recipient's parcel or package, including wording like got your package or your delivery is at mine.", "The message does not say the writer has the recipient's delivery."]}],
            ["Give a pickup location", {type: "noul", instruction: "Does the message itself identify a pickup place?",
                criteria: ["Words in the message name or describe a pickup place, including relative places such as my home, at mine, the porch, or a cafe.", "No pickup place is written. A pickup time or saying I have your package does not by itself specify a place."]}],
            ["Give a pickup time", {type: "noul", instruction: "Is any pickup timing provided in the message? Answer yes if: A time or window for pickup is given: a clock time, day, morning, after work, or similar timing. Answer no if: There is no timing for pickup.",
                criteria: ["", ""]}]),
        round("2-2", "A book worth borrowing", 140,
            "Recommend a book, give a reason to read it, and offer to lend your copy",
            ["Recommend a book", "Does the writer recommend a particular book by title?",
                "The writer recommends a book by title."],
            ["Give a reason to read it", "Does the writer give a specific reason to read the recommended book?",
                "The writer gives a specific reason the book is good."],
            ["Offer to lend your copy", "Does the writer offer to lend a book?",
                "The writer offers to lend a book."]),
        round("2-3", "The missing tool", 140,
            "Ask to borrow a screwdriver, say what it is for, and promise to return it",
            ["Ask for a screwdriver", "Does the writer ask to borrow a screwdriver?",
                "The writer asks to borrow a screwdriver."],
            ["Explain what you need it for", {type: "noul", instruction: "Does the message explain a use for the borrowed screwdriver?",
                criteria: ["A task for the screwdriver is named, such as tightening a door handle, fixing a hinge, or assembling furniture.", "No task for the screwdriver is described; simply asking to borrow it is insufficient."]}],
            ["Promise to return it", "Does the writer commit to returning the borrowed screwdriver?",
                "The writer promises to return the screwdriver."])
    ]},
    {id: 3, title: "Give it a reason", skill: "Connect a problem to a useful next step", estimatedDuration: "4-6 min", rounds: [
        round("3-1", "Different directions", 175,
            "Say the bridge is closed. Give another route, a landmark, and one hazard to watch for.",
            ["Explain the bridge closure", "Does the message say the bridge is closed?",
                "The message says the bridge is closed."],
            ["Suggest another route", "Does the message name an alternative route to the closed bridge?",
                "An alternative route to the closed bridge is suggested."],
            ["Name a landmark to follow", "Does the message name a landmark along the alternative route?",
                "A landmark along the alternative route is named."],
            ["Warn about a hazard", "Does the message warn about a specific hazard on the alternative route?",
                "A specific hazard on the alternative route is identified."]),
        round("3-2", "A thirsty fern", 175,
            "Ask someone to water your fern, say you are away, specify how much water, and thank them",
            ["Ask them to water the fern", "Does the writer ask the reader to water a fern?",
                "The writer asks someone to water a fern."],
            ["Say you are away", {type: "noul", instruction: "Does the writer say they are away from home?",
                criteria: ["They say they are away from home.", "They are at home, or no absence is stated."]}],
            ["Specify how much water", {type: "noul", instruction: "Is an amount of water described, even approximately?",
                criteria: ["A measure is given, including a cup of water (one cup), a splash, a spoonful, or a numeric quantity.", "There is no measure of water at all; only watering is mentioned."]}],
            ["Thank them for the favor", "Does the text include an expression of gratitude?",
                "The writer expresses gratitude."]),
        round("3-3", "One more chapter", 175,
            "Ask to keep a library book longer, name it, say you have not finished it, and give a return day",
            ["Ask for more borrowing time", {type: "noul", instruction: "Does the writer ask to extend a library book loan?",
                criteria: ["The writer asks for a longer library book loan.", "This detail is absent or contradicted."]}],
            ["Say you are still reading", {type: "noul", instruction: "Is there still some of the book left for the writer to read? Answer yes if: The writer has not finished reading, including saying that chapters or pages remain. Answer no if: Nothing says that any reading remains unfinished.",
                criteria: ["", ""]}],
            ["Give a return day", "Does the writer state a day they will return the book?",
                "The writer states a day they will return the book."],
            ["Name the book", {type: "choice", instruction: "Does the message contain the title of a book?",
                criteria: ["No", "Yes"]}])
    ]},
    {id: 4, title: "Plan a little", skill: "Turn a loose idea into an easy plan", estimatedDuration: "5-8 min", rounds: [
        round("4-1", "Rain check", 185,
            "Move a rooftop film indoors because of rain, name the new place, and keep the original time",
            ["Move the rooftop screening", {type: "noul", instruction: "Does the writer propose moving a rooftop film screening indoors?",
                criteria: ["", ""]}],
            ["Explain that rain is the reason", "Does the message say rain is the reason for changing the film location?",
                "Rain is given as the reason for moving the film screening."],
            ["Name a new indoor venue", "Does the message name a specific indoor place for the film screening?",
                "A particular indoor venue is proposed for the screening."],
            ["Keep the same start time", {type: "choice", instruction: "Does the message explicitly say the film will start at its original time?",
                criteria: ["No", "Yes"]}]),
        round("4-2", "The cake relay", 185,
            "Ask someone to collect a cake, name the bakery, give a collection time, and say who it is for",
            ["Ask for cake collection", "Does the writer ask someone to collect a cake?",
                "The writer asks the reader to collect a cake."],
            ["Name the bakery", "Does the message name the bakery where the cake is to be collected?",
                "The bakery where the cake can be collected is named."],
            ["Give a collection time", "Does the message give a time to collect the cake?",
                "A time to collect the cake is stated."],
            ["Name the recipient", "Does the message identify who the cake is for?",
                "The person the cake is for is identified."]),
        round("4-3", "A key detail", 185,
            "Tell a guest where the spare key is, how to open the door, where to leave the key, and wish them a good stay",
            ["Say where to find the key", {type: "choice", instruction: "What location information is given for the key?",
                criteria: ["No key location is given", "An initial place to find the key is given, possibly with later return instructions", "Only a place to return the key afterward is given"]}],
            ["Explain how to open the door", "Does the message explain an action needed to open the door?",
                "An action to open or unlock the door is explained."],
            ["Say where to leave the key", {type: "noul", instruction: "Does the message say where the guest should leave the key after using it?",
                criteria: ["The message says where to leave the key after use.", "This detail is absent or contradicted."]}],
            ["Welcome the guest", "Does the writer wish the guest a pleasant stay?",
                "The writer wishes the guest a pleasant stay."]),
        round("4-4", "Quiet rehearsal", 185,
            "Suggest a place and time to rehearse, ask someone to bring an instrument, and offer to bring the sheet music",
            ["Suggest a rehearsal place", "Does the message name a place to rehearse music?",
                "A place to rehearse music is proposed."],
            ["Suggest a rehearsal time", {type: "noul", instruction: "Does the message specify a time for the music rehearsal?",
                criteria: ["", ""]}],
            ["Ask them to bring an instrument", {type: "noul", instruction: "Does the writer ask someone to bring a particular musical instrument?",
                criteria: ["", ""]}],
            ["Offer to bring sheet music", "Does the writer offer to bring the sheet music?",
                "The writer offers to bring the sheet music."])
    ]},
    {id: 5, title: "Turn it around", skill: "Make a small setback easier to fix", estimatedDuration: "6-10 min", rounds: [
        round("5-1", "Wrong sandwich", 200,
            "Say which sandwich you ordered and what arrived, ask for the right one, and thank the server",
            ["Describe your original order", {type: "noul", instruction: "Does the writer name the filling they originally ordered or asked for? Answer yes if: A named sandwich filling is connected to the original order or request, such as I ordered cheese or I asked for ham. Answer no if: The original filling is not named. Mentioning what arrived or saying the one I ordered does not identify the original filling.",
                criteria: ["", ""]}],
            ["Say what actually arrived", {type: "noul", instruction: "Does the message identify the food that arrived?",
                criteria: ["The message says what the writer received, including a filling named after got or received.", "It does not say what arrived. Naming only the order or requested replacement is insufficient."]}],
            ["Ask for a replacement", "Does the writer ask for the sandwich they ordered to replace the incorrect one?",
                "The writer asks to replace the incorrect sandwich."],
            ["Thank the server", {type: "choice", instruction: "Does the message thank the recipient?",
                criteria: ["It contains no expression of thanks or appreciation.", "It includes thanks, thank you, appreciation, or another expression of gratitude."]}]),
        round("5-2", "A soggy notebook", 200,
            "Admit spilling water on a borrowed notebook, apologize, offer a new one, and offer to copy the notes",
            ["Admit spilling the water", "Does the writer say they spilled water on the notebook?",
                "The writer admits spilling water on the recipient's notebook."],
            ["Apologize", "Does the writer apologize for the damaged notebook?",
                "The writer apologizes for the damage."],
            ["Offer a new notebook", "Does the writer offer to replace the damaged notebook?",
                "The writer offers to replace the damaged notebook."],
            ["Offer to restore the notes", "Does the writer offer to copy the notes into a replacement notebook?",
                "The writer offers to copy the notes into the replacement."]),
        round("5-3", "Wrong room", 200,
            "Correct a meeting room, name the new room, keep the same time, and ask people to tell anyone missing the message",
            ["Rule out the old room", {type: "noul", instruction: "Does the message explicitly say the meeting will not be in its previously announced room?",
                criteria: ["The message explicitly rules out the previously announced meeting room.", "This detail is absent or contradicted."]}],
            ["Name the new room", {type: "noul", instruction: "Is the room to use for the meeting identified?",
                criteria: ["The message gives the new or replacement room, by name or number.", "No room to use is identified; only ruling out the old room is insufficient."]}],
            ["Keep the timing unchanged", {type: "choice", instruction: "Is the meeting's previous time kept?",
                criteria: ["An unchanged meeting time is not stated; a room change alone is not enough.", "The message says the time stays the same, including same time, still at a stated time, or no change to when it starts."]}],
            ["Ask them to pass the news on", "Does the writer ask recipients to tell people who may not see this message about the change?",
                "Recipients are asked to tell people who may miss this message about the change."]),
        round("5-4", "Restart, then reply", 200,
            "Suggest restarting a frozen app, ask them to report what happens, offer more help, and acknowledge the hassle",
            ["Suggest a restart", {type: "noul", instruction: "Does the writer suggest restarting an app?",
                criteria: ["", ""]}],
            ["Ask what happens afterward", "Does the writer ask the reader to report what happens after trying the suggested fix?",
                "The reader is asked to report what happens after the restart."],
            ["Offer more help", "Does the writer offer to help further with the app problem?",
                "The writer offers more help fixing the app problem."],
            ["Acknowledge the frustration", "Does the writer acknowledge that the app problem is frustrating or inconvenient?",
                "The writer acknowledges that the app problem is frustrating or inconvenient."])
    ]},
    {id: 6, title: "Help them choose", skill: "Put options and their useful differences into words", estimatedDuration: "8-12 min", rounds: [
        round("6-1", "Two routes to town", 225,
            "Offer a bus and a walk, compare their cost, say which is faster, and ask which they prefer",
            ["Offer the bus option", "Does the writer offer taking a bus as a travel option?",
                "Taking a bus is offered as a travel option."],
            ["Offer the walking option", "Does the writer offer walking as a travel option?",
                "Walking is offered as a travel option."],
            ["Compare the costs", "Does the message compare the cost of taking the bus with walking?",
                "The cost of the bus is compared with the cost of walking."],
            ["Compare journey times", {type: "choice", instruction: "Can the reader tell which journey is quicker from the message?",
                criteria: ["Journey times are not compared and both durations are not given. Cost alone does not show which is quicker.", "The message says which is faster, or gives different durations for both the bus and the walk so they can be compared."]}],
            ["Ask which they prefer", "Does the writer ask the reader which travel option they prefer?",
                "The reader is asked which travel option they prefer."]),
        round("6-2", "A desk with a catch", 225,
            "Recommend a desk, praise its storage, mention its size drawback, give its price, and suggest measuring first",
            ["Recommend a desk", "Does the writer recommend buying a desk?",
                "The writer recommends buying the desk."],
            ["Praise its storage", {type: "noul", instruction: "Does the message praise the desk's storage space?",
                criteria: ["", ""]}],
            ["Explain a size drawback", {type: "choice", instruction: "What does the message say about the desk's size?",
                criteria: ["No problem with its size is stated.", "It is too big or too small for the available space."]}],
            ["State the price", {type: "noul", instruction: "Does the message state the desk's price?",
                criteria: ["A price is stated for the desk.", "This detail is absent or contradicted."]}],
            ["Suggest measuring before buying", "Does the writer recommend measuring the available space before buying the desk?",
                "The writer advises measuring the available space before buying the desk."]),
        round("6-3", "The lunch vote", 225,
            "Offer soup or pasta for lunch, name a vegetarian option, offer to cook, and ask the group to vote",
            ["Offer soup", {type: "noul", instruction: "Does the writer suggest having soup for lunch?",
                criteria: ["The message satisfies this requirement: Soup offered.", "This requirement is not met by the message."]}],
            ["Offer pasta", {type: "noul", instruction: "Does the writer suggest having pasta as a lunch option?",
                criteria: ["Pasta is suggested as a lunch option.", "This detail is absent or contradicted."]}],
            ["Identify a vegetarian option", "Does the message explicitly identify one of the proposed dishes as vegetarian?",
                "One proposed dish is explicitly described as vegetarian."],
            ["Offer to cook", "Does the writer offer to cook the proposed lunch?",
                "The writer offers to cook lunch."],
            ["Ask the group to vote", "Does the writer ask the group to vote for a lunch option?",
                "The group is asked to vote for a lunch option."]),
        round("6-4", "A gift for a reader", 225,
            "Offer a named book or a bookshop voucher, praise a feature of the book, explain the voucher's benefit, and ask which they prefer",
            ["Suggest a book as a gift", {type: "noul", instruction: "Does the writer name a book they could give as a gift?", criteria: ["", ""]}],
            ["Offer a bookshop voucher", "Does the writer offer a bookshop voucher as an alternative gift?",
                "A bookshop voucher is offered as an alternative gift."],
            ["Explain why to choose the book", "Does the message describe an appealing feature of the book itself?",
                "The book's writing, illustrations, or another feature is praised."],
            ["Explain why to choose the voucher", "Does the message say why the recipient might prefer a bookshop voucher?",
                "A benefit of the voucher, such as choosing a book themselves, is stated."],
            ["Ask which they prefer", {type: "noul", instruction: "Does the writer ask which gift the recipient prefers?",
                criteria: ["The message satisfies this requirement: The recipient decides.", "This requirement is not met by the message."]}])
    ]},
    {id: 7, title: "Make the handoff", skill: "Give the next person what they need to take over", estimatedDuration: "10-16 min", rounds: [
        round("7-1", "Cat-sitting notes", 245,
            "Explain your cat's food, feeding time, hiding spot, water needs, and how to contact you",
            ["Say what the cat eats", {type: "noul", instruction: "Does the message identify food for the cat?",
                criteria: ["A food type or name is given, such as dry food, wet food, kibble, or a brand.", "No food type or name is given. Just saying feed the cat is insufficient."]}],
            ["Say when to feed the cat", {type: "noul", instruction: "Does the message specify when to feed the cat?",
                criteria: ["", ""]}],
            ["Say where the cat hides", "Does the message identify a place where the cat hides?",
                "The place where the cat hides is described."],
            ["Explain how to care for its water", "Does the message tell the reader to provide or refresh the cat's water?",
                "The reader is asked to provide or refresh water for the cat."],
            ["Give a way to reach you", {type: "noul", instruction: "Does the writer say how the reader can contact them?",
                criteria: ["", ""]}]),
        round("7-2", "The repair handoff", 245,
            "Describe a broken lamp, say what you tried, name a part to check, give its location, and ask for an update",
            ["Describe the lamp problem", "Does the message describe what is wrong with a lamp?",
                "A fault with the lamp is described."],
            ["Say what fix you already tried", "Does the writer name something they already tried to fix the lamp?",
                "The writer names a fix already tried on the lamp."],
            ["Name a part to inspect", {type: "choice", instruction: "Does the writer ask for a particular lamp part to be checked?",
                criteria: ["This detail is absent or contradicted.", "A particular lamp part is identified for inspection."]}],
            ["Say where the lamp is", {type: "choice", instruction: "Does the message identify a physical place where the lamp is?",
                criteria: ["No place for the lamp is stated. Mentioning a lamp part or attempted repair is not its location.", "A place for the lamp is stated, such as on my desk, on a table, in a room, or another described spot."]}],
            ["Ask for an update", "Does the writer ask to hear the result of the lamp inspection?",
                "The writer asks to hear what the lamp inspection finds."]),
        round("7-3", "Market stall shift", 245,
            "Say what the stall sells, give a price, explain payment, name the next volunteer, and give handover time",
            ["Name the product", "Does the message name what the market stall sells?",
                "A product sold at the market stall is named."],
            ["Give a selling price", "Does the message give a price for a product at the stall?",
                "A selling price for the product is stated."],
            ["Explain how to take payment", {type: "noul", instruction: "Does the message say how customers can pay?",
                criteria: ["", ""]}],
            ["Name who takes over", "Does the message name the person taking over the stall?",
                "The person taking over the stall is named."],
            ["Say when to hand over", {type: "noul", instruction: "Does the message give a time for the stall handover?",
                criteria: ["A time for the stall handover is stated.", "This detail is absent or contradicted."]}]),
        round("7-4", "Read and compare", 245,
            "Name a book and a page goal, set a discussion day and place, and ask your friend to bring notes",
            ["Name a book", "Does the message identify a book by title?",
                "A book title is stated."],
            ["Set a page target", "Does the message specify a number of pages to read?",
                "A number of pages to read is stated."],
            ["Set a discussion day", "Does the message say which day to discuss the book?",
                "A day for discussing the book is given."],
            ["Name a meeting place", {type: "noul", instruction: "Does the message specify where to meet for the book discussion? Judge the meaning; ordinary paraphrases and pronouns count. Do not assume missing information.",
                criteria: ["", ""]}],
            ["Ask them to bring notes", {type: "noul", instruction: "Does the writer ask the reader to bring notes?", criteria: ["", ""]}]),
        round("7-5", "A recipe rescue", 245,
            "Name a missing ingredient, suggest a substitute, give its amount, explain its effect, and say when to add it",
            ["Name a missing ingredient", {type: "choice", instruction: "What ingredient problem does the text describe?",
                criteria: ["No missing ingredient is identified.", "The writer has run out of a named ingredient."]}],
            ["Name a substitute", {type: "noul", instruction: "Does the writer suggest a particular substitute for the missing ingredient? Judge only the words actually written. If the text does not say this, answer no.",
                criteria: ["", ""]}],
            ["Specify how much substitute", {type: "noul", instruction: "Does the message give a quantity of the substitute ingredient?",
                criteria: ["An amount for the replacement ingredient is given, such as two tablespoons, a cup, grams, or a ratio.", "No amount of the substitute is given."]}],
            ["Explain its effect on the food", "Does the message explain how the substitute changes the finished food?",
                "The effect of the substitution on the finished dish is described."],
            ["Say when to add it", "Does the message say which cooking step comes before or after adding the substitute?",
                "The text states when to add the replacement ingredient."])
    ]},
    {id: 8, title: "Make room for both", skill: "Find a practical plan for two different needs", estimatedDuration: "12-18 min", rounds: [
        round("8-1", "Window diplomacy", 255,
            "One person wants fresh air; another is cold. Acknowledge both, propose airing briefly, give a duration, and offer to close it.",
            ["Explain the need for fresh air", "Does the message acknowledge someone wants fresh air?",
                "The message acknowledges that someone wants fresh air."],
            ["Acknowledge someone is cold", {type: "noul", instruction: "Does the message acknowledge someone is feeling cold?",
                criteria: ["", ""]}],
            ["Propose a brief airing", "Does the writer suggest opening a window temporarily?",
                "Opening a window temporarily is proposed."],
            ["Say how long to air the room", {type: "noul", instruction: "Does the message specify how long to keep the window open?",
                criteria: ["", ""]}],
            ["Offer to close the window", "Does the writer offer to close the window afterward?",
                "The writer offers to close the window afterward."]),
        round("8-2", "The shared shelf", 255,
            "Acknowledge two people need shelf space, suggest a split, offer to move your things, and ask for agreement",
            ["Explain your storage need", "Does the writer state that they need shelf space for their belongings?",
                "The writer says they need shelf space for their belongings."],
            ["Acknowledge their storage need", "Does the message acknowledge the other person needs shelf space?",
                "The other person's need for shelf space is acknowledged."],
            ["Propose a specific division", "Does the writer propose a specific division of the shelf space?",
                "A specific division of shelf space is proposed."],
            ["Offer to move your things", "Does the writer offer to move their own belongings to make the shelf plan work?",
                "The writer offers to move their own things to make space."],
            ["Ask for their agreement", {type: "noul", instruction: "Does the writer ask whether the proposed shelf arrangement is acceptable? Judge only the words actually written. If the text does not say this, answer no.",
                criteria: ["", ""]}]),
        round("8-3", "The weekend trade", 255,
            "Ask to swap shifts, name both shifts, mention your other commitment, and thank them",
            ["Ask to swap shifts", "Does the writer ask to swap work shifts?",
                "The writer requests a work shift swap."],
            ["Identify your shift", {type: "choice", instruction: "When does the writer need their shift covered?",
                criteria: ["No day is stated for the shift they need covered.", "The writer requests cover on a stated day."]}],
            ["Offer a shift in return", "Does the writer offer to cover a specific shift for the other person in return?",
                "A specific shift is offered in return."],
            ["Mention your other commitment", "Does the writer mention a personal event or commitment they need to attend?",
                "A personal event or commitment the writer needs to attend is named."],
            ["Thank them", {type: "choice", instruction: "Does the message thank the recipient?",
                criteria: ["It contains no expression of thanks or appreciation.", "It includes thanks, thank you, appreciation, or another expression of gratitude."]}]),
        round("8-4", "Game night for everyone", 255,
            "Suggest a game, explain how a beginner can join, include an experienced player, set a length, and invite everyone",
            ["Name a game", "Does the writer propose playing a specific game?",
                "A particular game is proposed."],
            ["Explain how beginners can join", "Does the message propose concrete help for a beginner to participate?",
                "A concrete way to help beginners participate is described."],
            ["Give an experienced player a role", "Does the message propose a specific role for an experienced player?",
                "A specific role for an experienced player is proposed."],
            ["Set a session length", {type: "noul", instruction: "Does the message give a length of time for playing?",
                criteria: ["A session duration is stated, such as half an hour, an hour, or a number of minutes.", "No playing duration is stated. A start time alone is not a duration."]}],
            ["Invite everyone", {type: "choice", instruction: "Is the group invited to play?",
                criteria: ["No", "Yes"]}]),
        round("8-5", "The photo exchange", 255,
            "Ask for a group photo, explain your use, offer one of yours, say how to send it, and ask before posting theirs publicly",
            ["Ask for a group photo", "Does the writer ask the reader for a group photo?",
                "The writer asks for a group photo."],
            ["Explain its intended use", {type: "choice", instruction: "Does the writer explain what they want the group photo for?",
                criteria: ["This detail is absent or contradicted.", "The writer explains what they want the group photo for."]}],
            ["Offer a photo in return", "Does the writer offer a photo in return?",
                "The writer offers a photo in return."],
            ["Suggest a transfer method", {type: "choice", instruction: "Does the message specify a way to send the photos?",
                criteria: ["This detail is absent or contradicted.", "A method of sending the photos is specified."]}],
            ["Ask for permission to post it", {type: "choice", instruction: "What permission does the writer request for the recipient's photo?",
                criteria: ["No permission to publish the photo is requested.", "Permission to post the photo publicly is requested."]}])
    ]},
    {id: 9, title: "Six useful details", skill: "Fit a complete small project into one message", estimatedDuration: "15-24 min", rounds: [
        round("9-1", "A tiny exhibition", 290,
            "Invite someone to a photo show: name its theme, venue, date, entry price, and a reason to visit",
            ["Invite them to the show", "Does the writer invite the reader to a photo exhibition?",
                "The reader is invited to a photo exhibition."],
            ["Name an exhibition theme", {type: "noul", instruction: "Does the message say what the photographs show?",
                criteria: ["A subject or theme is named, such as wildlife, portraits, city life, landscapes, or another topic.", "No subject of the photographs is given."]}],
            ["Name a venue", "Does the message name where the photo exhibition takes place?",
                "The exhibition's venue is stated."],
            ["Set a date", "Does the message give a day or date for the photo exhibition?",
                "A day or date for the exhibition is given."],
            ["State the entry price", "Does the message state the admission price or that admission is free?",
                "The admission price or free entry is stated."],
            ["Give a reason to visit", "Does the message give a specific reason the reader might enjoy visiting the exhibition?",
                "A specific reason to visit the exhibition is offered."]),
        round("9-2", "A garden from scraps", 290,
            "Propose a herb garden, choose a reused container, name a herb and location, offer a task, and ask for help",
            ["Propose a garden", "Does the writer propose starting a herb garden?",
                "Starting a herb garden is proposed."],
            ["Choose a reused container", "Does the message propose repurposing an existing object as a planting container?",
                "An existing object is to be reused as a planter."],
            ["Name a herb to grow", "Does the message name a specific herb to grow?",
                "A specific herb to grow is named."],
            ["Suggest a growing location", "Does the message say where the herbs will grow?",
                "A place to grow the herbs is stated."],
            ["Offer to take on a task", "Does the writer say which gardening task they will do?",
                "The writer states a specific gardening task they will do."],
            ["Ask for their help", "Does the writer ask the other person to help with the herb garden?",
                "The writer asks someone else to help with the garden."]),
        round("9-3", "The almost-perfect stay", 290,
            "Review a stay: praise the bed and host, name a problem, its impact, a fix, and whether you would return",
            ["Praise the bed's comfort", {type: "noul", instruction: "Does the review say the bed was comfortable?",
                criteria: ["The bed is described as comfortable.", "This detail is absent or contradicted."]}],
            ["Praise something the host did", "Does the review praise something the host did?",
                "Something the host did is praised."],
            ["Describe a concrete problem", "Does the writer describe a problem with the room or its contents?",
                "A concrete fault with the room is identified."],
            ["Explain its effect on you", "Does the reviewer explain how the problem affected them?",
                "The reviewer describes how the problem affected them."],
            ["Propose an improvement", {type: "noul", instruction: "Does the reviewer suggest a specific improvement addressing the problem?",
                criteria: ["A specific improvement addressing the problem is suggested.", "This detail is absent or contradicted."]}],
            ["Say whether you would return", {type: "noul", instruction: "Does the reviewer explicitly say whether they would stay there again?",
                criteria: ["The message satisfies this requirement: A return decision.", "This requirement is not met by the message."]}]),
        round("9-4", "A local history hunt", 290,
            "Suggest a history walk past a station and clock tower, name a feature to notice at each, and ask a friend to lead part",
            ["Propose a history walk", {type: "noul", instruction: "Does the writer suggest taking a walk to explore local history?",
                criteria: ["", ""]}],
            ["Include a station stop", "Does the writer propose visiting a station on the history walk?",
                "Visiting a station is proposed."],
            ["Include a clock tower stop", "Does the writer propose visiting a clock tower on the history walk?",
                "Visiting a clock tower is proposed."],
            ["Name a station feature", {type: "noul", instruction: "Does the message name something to notice at the station?",
                criteria: ["Yes", "No"]}],
            ["Name a clock tower feature", {type: "noul", instruction: "Does the message name a historical feature to look for at the clock tower?",
                criteria: ["", ""]}],
            ["Invite a friend to lead part", "Does the writer ask the friend to lead part of the walk?",
                "The reader is invited to lead part of the walk."]),
        round("9-5", "A repair cafe", 290,
            "Invite neighbors to a repair cafe, name an item to bring, give place and time, offer a skill, and ask for volunteers",
            ["Invite the neighbors", "Does the writer invite neighbors to a repair cafe or community repair event?",
                "Neighbors are invited to a community repair event."],
            ["Say what to bring", "Does the writer name something people can bring to be repaired?",
                "A kind of broken item to bring is named."],
            ["Name a repair venue", "Does the message give a place for the repair event?",
                "The repair event's venue is named."],
            ["Set a repair time", "Does the message specify when the repair event takes place?",
                "A time for the repair event is given."],
            ["Offer a skill", "Does the writer offer a specific repair skill of their own?",
                "The writer offers a specific repair skill of their own."],
            ["Ask for volunteers", "Does the writer ask for volunteers to help run the repair event?",
                "Volunteers are asked to help with the repair event."]),
        round("9-6", "A birthday without stuff", 290,
            "Propose an experience as a birthday gift, tailor it to a hobby, give its cost, offer to organize, suggest a date, and ask for approval",
            ["Suggest an experience gift", "Does the writer propose an activity as a birthday present?",
                "An activity is proposed as a birthday gift."],
            ["Link it to their interest", "Does the message connect the proposed birthday activity to the recipient's existing interest?",
                "The birthday activity is connected to the recipient's interests."],
            ["State the cost", {type: "noul", instruction: "Does the message give the cost of the birthday experience?",
                criteria: ["A cost for the birthday activity is given.", "This detail is absent or contradicted."]}],
            ["Offer to organize it", "Does the writer offer to organize or book the birthday experience?",
                "The writer offers to arrange the birthday activity."],
            ["Suggest a date", "Does the message specify when the birthday activity could take place?",
                "A day or date for the birthday activity is proposed."],
            ["Ask for their approval", "Does the writer ask whether the birthday plan suits the recipient?",
                "The recipient is asked whether the birthday plan suits them."])
    ]},
    {id: 10, title: "Make a little go far", skill: "Solve a practical constraint with a compact proposal", estimatedDuration: "18-30 min", rounds: [
        round("10-1", "A bench on a budget", 305,
            "Set a bench budget, price an oak and a pine option, choose one you can afford, praise a useful feature, and offer to collect it",
            ["Set a spending limit", {type: "noul", instruction: "Does the message state how much money is available to spend?",
                criteria: ["", ""]}],
            ["Give an oak bench price", {type: "noul", instruction: "Does the message give the price of an oak bench?",
                criteria: ["An oak bench's price is stated.", "This detail is absent or contradicted."]}],
            ["Give a pine bench price", "Does the message give the price of a pine bench?",
                "A pine bench's price is stated."],
            ["Choose an affordable option", "Does the writer choose an option within their stated budget?",
                "The writer chooses a bench within their stated budget."],
            ["Praise a useful feature", "Does the writer name a practical advantage of the bench they chose?",
                "A useful feature of the chosen bench is explained."],
            ["Offer to collect it", "Does the writer offer to collect the chosen bench?",
                "The writer offers to collect the bench."]),
        round("10-2", "A workshop in half the time", 305,
            "Shorten a workshop: keep its main exercise, cut a slideshow that repeats the notes, offer the notes, and ask for feedback",
            ["Explain that less time is available", {type: "noul", instruction: "Does the writer say there is less time available for the workshop?",
                criteria: ["", ""]}],
            ["Name an activity to keep", {type: "noul", instruction: "Does the writer say which workshop activity to keep?",
                criteria: ["", ""]}],
            ["Name an activity to remove", "Does the writer identify a workshop activity to remove?",
                "The slideshow is to be removed from the workshop."],
            ["Explain the cut", "Does the message say the slideshow repeats information available elsewhere?",
                "The slideshow repeats information already in the notes or handout."],
            ["Offer the notes", "Does the writer offer participants notes or a handout?",
                "The writer offers participants notes or a handout."],
            ["Ask for feedback", "Does the writer ask for feedback on the shorter workshop plan?",
                "The writer asks for feedback on the shorter workshop plan."]),
        round("10-3", "A menu for two needs", 305,
            "Plan a meal for a vegetarian and someone avoiding gluten: name both needs, suggest a dish, explain both fits, and offer to cook",
            ["Acknowledge the vegetarian guest", {type: "noul", instruction: "Does the message explicitly mention a guest is vegetarian?",
                criteria: ["", ""]}],
            ["Acknowledge the gluten-free guest", {type: "choice", instruction: "Does the message say someone avoids gluten?",
                criteria: ["This detail is absent or contradicted.", "A guest is described as avoiding gluten."]}],
            ["Propose a meal", "Does the writer propose a specific dish to serve?",
                "A particular dish is proposed for the meal."],
            ["Explain why it is vegetarian", {type: "noul", instruction: "Does the message explicitly explain that the proposed dish contains no meat?",
                criteria: ["The proposed dish is explicitly described as containing no meat.", "This detail is absent or contradicted."]}],
            ["Explain why it avoids gluten", {type: "noul", instruction: "Does the message explicitly explain that the proposed dish is gluten-free?",
                criteria: ["", ""]}],
            ["Offer to cook", "Does the writer offer to cook the proposed meal?",
                "The writer offers to cook the meal."]),
        round("10-4", "A project worth trying", 305,
            "Pitch a tool-sharing shelf: explain the idea, its benefit, where it goes, one rule, a trial length, and how to judge it",
            ["Explain the sharing idea", "Does the writer propose a shelf where people can borrow shared tools?",
                "A shelf for lending shared tools is proposed."],
            ["Describe a benefit", "Does the message explain a benefit of sharing tools?",
                "A benefit of sharing tools is explained."],
            ["Name a location", "Does the message name a place for the tool-sharing shelf?",
                "A place for the tool shelf is named."],
            ["Set a borrowing rule", {type: "choice", instruction: "Does the message state a concrete rule for borrowing the tools?",
                criteria: ["This detail is absent or contradicted.", "A concrete tool-borrowing rule is stated."]}],
            ["Set a trial duration", {type: "choice", instruction: "Does the message specify how long to trial the tool-sharing scheme?",
                criteria: ["No", "Yes"]}],
            ["Define a measure of success", "Does the message propose a concrete way to assess whether the tool-sharing trial works?",
                "A concrete measure for judging the trial's success is proposed."]),
        round("10-5", "Room for a beginner", 305,
            "Invite a novice to a hike, name the route, explain why it suits them, set a pace, offer equipment, and plan a rest stop",
            ["Invite a novice", "Does the writer invite a beginner to go hiking?",
                "A beginner is invited on a hike."],
            ["Name a route", {type: "choice", instruction: "Does the message name the path or trail for the hike?",
                criteria: ["No", "Yes"]}],
            ["Explain why the route suits them", "Does the message give a reason the proposed hike is suitable for a beginner?",
                "A reason the hike suits a beginner is explained."],
            ["Suggest a manageable pace", "Does the writer propose a pace intended to suit the beginner?",
                "A pace suitable for the beginner is proposed."],
            ["Offer equipment", "Does the writer offer to lend the beginner specific hiking equipment?",
                "The writer offers to lend particular hiking equipment."],
            ["Plan a rest stop", "Does the message propose a specific rest stop during the hike?",
                "A specific rest stop is proposed."]),
        round("10-6", "The book swap", 305,
            "Propose a book swap, give place and time, explain what to bring, say how books are exchanged, and offer leftover books to charity",
            ["Propose a book swap", "Does the writer propose a book swap event?",
                "A book swap event is proposed."],
            ["Name a swap location", {type: "choice", instruction: "Does the message name where the book swap happens?",
                criteria: ["The swap has no named venue.", "A venue such as a hall, house, library, or other place is named for the swap."]}],
            ["Set a swap time", "Does the message give a time for the book swap?",
                "A time for the book swap is given."],
            ["Say what to bring", "Does the message ask people to bring books they have finished reading?",
                "People are asked to bring books they have finished reading."],
            ["Explain how the swap works", "Does the message state a concrete rule for exchanging books?",
                "A concrete rule for exchanging the books is stated."],
            ["Offer to donate leftover books", "Does the writer propose giving leftover books to charity?",
                "Leftover books are to be donated to charity."])
    ]},
    {id: 11, title: "The final edit", skill: "Eight new briefs; seven goals each. Find the shortest complete version.", estimatedDuration: "25-40 min", rounds: [
        round("11-1", "A cinema for one night", 370,
            "Plan a community film night: film, venue, date, ticket price, an accessibility feature, snacks, and a request for helpers",
            ["Choose a film", "Does the message identify a movie that will be shown?",
                "A film to screen is named."],
            ["Name a venue", {type: "choice", instruction: "Does the message identify a venue for the film night?",
                criteria: ["No actual venue is named. A film title, screen, ticket price, or accessibility statement alone is not a venue.", "A place for watching the film is named, separately from the movie title. For example, at the hall or in a house names a venue."]}],
            ["Set a date", {type: "noul", instruction: "Does the message give a date or day for the film screening?",
                criteria: ["", ""]}],
            ["State the ticket price or free entry", {type: "noul", instruction: "Does the message say how much tickets cost or that the screening is free?",
                criteria: ["Ticket prices or free admission are explained.", "This detail is absent or contradicted."]}],
            ["Describe an accessibility feature", "Does the message state a specific accessibility feature at the film event?",
                "A specific accessibility feature is mentioned."],
            ["Plan the snacks", {type: "choice", instruction: "Does the message mention food for the film night?",
                criteria: ["No", "Yes"]}],
            ["Ask for help", "Does the writer ask for helpers for the film event?",
                "The writer asks for help with the film event."]),
        round("11-2", "A little shop online", 370,
            "Pitch a local shop's website: products, customers, a benefit, ordering, collection, launch day, and an invitation to try it",
            ["Say what is sold", {type: "noul", instruction: "Does the message identify what the shop offers for sale?",
                criteria: ["A product type is named, including in a phrase such as candle website, book shop, or a similar description.", "No product or type of goods is identified."]}],
            ["Describe who it is for", {type: "choice", instruction: "Does the message identify the shop's customers?",
                criteria: ["No intended customer group is identified.", "The intended customers are named, described, or addressed directly, such as local gift shoppers."]}],
            ["Explain why to use it", "Does the message explain a benefit of using the shop website?",
                "A benefit of using the shop website is explained."],
            ["Explain how to order", "Does the message explain how to place an order?",
                "The way to place an order is explained."],
            ["Explain how to collect", "Does the message explain how customers receive or collect an order?",
                "The way to receive or collect an order is explained."],
            ["Say when it opens", {type: "noul", instruction: "Does the message state a launch day or date for the website?",
                criteria: ["A launch day or date is stated.", "This detail is absent or contradicted."]}],
            ["Invite people to try it", "Does the writer invite the reader to try the shop website?",
                "The reader is invited to try the website."]),
        round("11-3", "The neighborhood time bank", 370,
            "Propose swapping skills: your offer, what you need, equal time in return, a meeting place, a time, and an invitation to join",
            ["Propose swapping skills", "Does the writer propose exchanging skills or services with neighbors?",
                "Exchanging skills or services with neighbors is proposed."],
            ["Offer your skill", "Does the writer offer a specific skill they can teach or provide?",
                "The writer offers a specific skill or service."],
            ["Say what skill you need", "Does the writer name a skill or service they would like in return?",
                "The writer names a skill or service they need."],
            ["Propose an equal-time exchange", {type: "noul", instruction: "Does the message propose exchanging equal amounts of time?",
                criteria: ["The message satisfies this requirement: An exchange rule.", "This requirement is not met by the message."]}],
            ["Name a meeting place", "Does the message name a place to meet for the skill exchange?",
                "A place to meet for the exchange is stated."],
            ["Set a meeting time", "Does the message specify when to meet for the skill exchange?",
                "A time to meet for the exchange is given."],
            ["Invite others to join", "Does the writer invite other people to join the skill exchange?",
                "Others are invited to join the skill exchange."]),
        round("11-4", "The science club challenge", 370,
            "Plan an experiment: duration, one condition kept equal, prediction, materials, method, measurement, and a partner invitation",
            ["Set a test duration", {type: "noul", instruction: "Does the message say how long to run the experiment?",
                criteria: ["A duration for the experiment is stated.", "This detail is absent or contradicted."]}],
            ["Name a condition to keep equal", "Does the message name a condition kept the same for both experimental groups?",
                "A particular condition is kept the same for both groups."],
            ["Make a prediction", "Does the writer predict the outcome of the experiment?",
                "The writer predicts the experiment's result."],
            ["Name the materials", "Does the message name materials needed for the experiment?",
                "Materials for the experiment are named."],
            ["Describe a test method", "Does the message describe how to test the experimental question?",
                "The method for testing the question is described."],
            ["Say what to measure", "Does the message specify what to measure in the experiment?",
                "Something to measure in the experiment is specified."],
            ["Invite a partner", "Does the writer invite someone to take part in the experiment?",
                "Someone is invited to join the experiment."]),
        round("11-5", "A pop-up museum", 370,
            "Plan a museum of everyday objects: theme, one exhibit, its story, venue, visiting time, entry cost, and a request for contributions",
            ["Name a museum theme", "Does the message name a theme for the proposed museum display?",
                "A theme for the museum display is given."],
            ["Name an exhibit", "Does the message name a specific object to exhibit?",
                "An object to exhibit is named."],
            ["Tell its story", {type: "noul", instruction: "Does the message tell something that happened in the exhibit object's past?",
                criteria: ["A specific past use, memory, or history is given, including a length of time the object was used.", "No specific past use, memory, or history is described. Only calling an object old, or saying it is mine, is insufficient."]}],
            ["Name a display venue", "Does the message name a place for the museum display?",
                "A venue for the display is named."],
            ["Set visiting hours", {type: "choice", instruction: "Does the message say when people can visit the museum?",
                criteria: ["This detail is absent or contradicted.", "Visiting times are stated."]}],
            ["State the entry cost", "Does the message specify the cost of admission or that admission is free?",
                "The cost of entry or free admission is stated."],
            ["Ask for contributions", "Does the writer ask others to contribute objects to the display?",
                "Others are asked to contribute objects to the display."]),
        round("11-6", "The two-stop escape", 370,
            "Plan a day trip: town or city, transport, a railway museum and city walls, a reason to visit each, and a return time",
            ["Name a destination", "Does the message name a town or city for the day trip?",
                "The town or city to visit is named."],
            ["Explain how to get there", "Does the message name transport for reaching the day-trip destination?",
                "Transport to reach the destination is specified."],
            ["Include a railway museum visit", "Does the writer propose visiting a railway museum on the trip?",
                "Visiting a railway museum is proposed."],
            ["Explain why to visit the museum", "Does the message give a reason to visit the railway museum?",
                "A reason to visit the railway museum is given."],
            ["Include a city walls visit", "Does the writer propose visiting city walls on the trip?",
                "Visiting city walls is proposed."],
            ["Explain why to visit the walls", "Does the message give a reason to visit the city walls?",
                "A reason to visit the city walls is given."],
            ["Say when to return", {type: "choice", instruction: "What does the message establish?",
                criteria: ["No return time is stated.", "A return time is given, including back at six, home at a stated time, or similar wording."]}]),
        round("11-7", "A club that lasts", 370,
            "Start a drawing club: audience, place, schedule, materials, beginner support, cost, and a way to join",
            ["Describe who the club is for", "Does the message identify who the drawing club is intended for?",
                "The drawing club's intended audience is described."],
            ["Name a club venue", "Does the message name a meeting place for the drawing club?",
                "A meeting venue is named."],
            ["Set a regular schedule", "Does the message give a recurring meeting schedule for the drawing club?",
                "A recurring schedule for the drawing club is given."],
            ["Explain what materials are needed", "Does the message say what drawing materials to bring or what will be provided?",
                "Drawing materials to bring or available materials are specified."],
            ["Explain how beginners get help", "Does the message explain a concrete way beginners will be helped at the drawing club?",
                "A concrete form of help for beginners is explained."],
            ["State the membership cost", "Does the message specify the cost of joining the drawing club or that it is free?",
                "Membership costs or free membership are stated."],
            ["Explain how to join", "Does the message tell people how to join the drawing club?",
                "A way to sign up for the club is given."]),
        round("11-8", "A good idea made real", 370,
            "Pitch a street library: purpose, location, book rule, weather protection, your task, an opening date, and a request for help",
            ["Explain the library's purpose", "Does the message explain that the street library lets people share books?",
                "Sharing books with neighbors is the purpose of the street library."],
            ["Name a library location", {type: "noul", instruction: "Does the message name a location for the street library? Judge the meaning; ordinary paraphrases and pronouns count. Do not assume missing information.",
                criteria: ["", ""]}],
            ["Set a book-sharing rule", "Does the message state a concrete rule for using the street library?",
                "A concrete book-sharing rule is given."],
            ["Plan protection from the weather", "Does the message propose how to protect the street library books from the weather?",
                "A way to protect the books from weather is proposed."],
            ["Offer your contribution", "Does the writer commit to a specific task to create the street library?",
                "The writer offers to do a specific setup task."],
            ["Set an opening date", {type: "noul", instruction: "Does the message give a day or date to open the street library?",
                criteria: ["An opening day or date is proposed.", "This detail is absent or contradicted."]}],
            ["Ask for help with a setup task", {type: "noul", instruction: "Does the writer request help with a specific task for the street library?",
                criteria: ["The writer asks someone else to help set up the library.", "This detail is absent or contradicted."]}])
    ]}
];
